// Mock data matching Sanity schema structure
export const mockPersonalInfo = {
  _id: 'personal-info',
  name: 'Aftab Pathan',
  title: 'Full Stack Developer',
  location: 'Mumbai, India',
  summary: 'Passionate full-stack developer with expertise in modern web technologies. Creating innovative solutions and seamless user experiences with a focus on performance and user-centric design.',
  avatar: '/images/avatar.svg',
  email: 'aftab.pathan@example.com',
  phone: '+91 98765 43210',
  linkedin: 'https://linkedin.com/in/aftabpathan',
  github: 'https://github.com/aftab0khan021',
  website: 'https://aftabpathan.dev',
};

export const mockExperiences = [
  {
    _id: 'exp-1',
    title: 'Senior Full Stack Developer',
    company: 'Tech Innovations Ltd',
    location: 'Mumbai, India',
    type: 'full-time',
    startDate: '2022-06-01',
    endDate: null,
    current: true,
    description: [
      'Led development of scalable web applications serving 100K+ users using React, Node.js, and MongoDB',
      'Architected microservices infrastructure reducing system downtime by 40%',
      'Mentored junior developers and established coding standards and best practices',
      'Implemented CI/CD pipelines improving deployment efficiency by 60%'
    ],
    technologies: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'Docker', 'AWS', 'GraphQL'],
    logo: '/images/companies/tech-innovations.jpg',
    order: 0,
    featured: true,
    isActive: true,
  },
  {
    _id: 'exp-2',
    title: 'Full Stack Developer',
    company: 'Digital Solutions Inc',
    location: 'Remote',
    type: 'full-time',
    startDate: '2020-08-01',
    endDate: '2022-05-31',
    current: false,
    description: [
      'Developed responsive web applications using React and Express.js',
      'Collaborated with design team to implement pixel-perfect UI components',
      'Optimized application performance resulting in 50% faster load times',
      'Integrated third-party APIs and payment gateways'
    ],
    technologies: ['React', 'Express.js', 'PostgreSQL', 'JavaScript', 'Material-UI', 'Stripe API'],
    logo: '/images/companies/digital-solutions.jpg',
    order: 1,
    featured: true,
    isActive: true,
  },
  {
    _id: 'exp-3',
    title: 'Junior Web Developer',
    company: 'StartupCo',
    location: 'Mumbai, India',
    type: 'internship',
    startDate: '2019-06-01',
    endDate: '2020-07-31',
    current: false,
    description: [
      'Built responsive websites using HTML, CSS, JavaScript, and jQuery',
      'Assisted in database design and implementation',
      'Participated in code reviews and learned industry best practices'
    ],
    technologies: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL'],
    logo: '/images/companies/startupco.jpg',
    order: 2,
    featured: false,
    isActive: true,
  },
];

export const mockProjects = [
  {
    _id: 'project-1',
    name: 'E-Commerce Platform',
    description: 'A full-featured e-commerce platform with real-time inventory management, payment processing, and admin dashboard.',
    longDescription: [
      'Built a comprehensive e-commerce solution serving over 10,000 products with real-time inventory tracking',
      'Implemented secure payment processing using Stripe API with support for multiple currencies',
      'Created an intuitive admin dashboard for inventory management, order tracking, and analytics',
      'Designed responsive UI/UX ensuring seamless experience across all devices'
    ],
    image: '/images/projects/ecommerce-platform.jpg',
    gallery: [
      '/images/projects/ecommerce-1.jpg',
      '/images/projects/ecommerce-2.jpg',
      '/images/projects/ecommerce-3.jpg'
    ],
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe API', 'Redux', 'Material-UI', 'Express.js'],
    tags: ['E-commerce', 'Full Stack', 'Payment Integration', 'Admin Panel'],
    liveUrl: 'https://ecommerce-demo.aftabpathan.dev',
    githubUrl: 'https://github.com/aftab0khan021/ecommerce-platform',
    category: 'web-app',
    featured: true,
    order: 0,
    isActive: true,
    completedDate: '2023-12-15',
    status: 'completed',
  },
  {
    _id: 'project-2',
    name: 'Task Management App',
    description: 'A collaborative task management application with real-time updates, team collaboration features, and project tracking.',
    longDescription: [
      'Developed a real-time collaborative task management platform supporting team workflows',
      'Implemented WebSocket connections for live updates and notifications',
      'Created advanced filtering, sorting, and search capabilities for enhanced productivity',
      'Built comprehensive reporting and analytics dashboard for project insights'
    ],
    image: '/images/projects/task-management.jpg',
    gallery: [
      '/images/projects/task-1.jpg',
      '/images/projects/task-2.jpg'
    ],
    technologies: ['Vue.js', 'Firebase', 'Socket.io', 'Vuetify', 'Node.js'],
    tags: ['Productivity', 'Real-time', 'Collaboration', 'Dashboard'],
    liveUrl: 'https://taskapp-demo.aftabpathan.dev',
    githubUrl: 'https://github.com/aftab0khan021/task-management',
    category: 'web-app',
    featured: true,
    order: 1,
    isActive: true,
    completedDate: '2023-09-22',
    status: 'completed',
  },
  {
    _id: 'project-3',
    name: 'Weather Analytics Dashboard',
    description: 'A comprehensive weather analytics platform with historical data, forecasts, and interactive visualizations.',
    longDescription: [
      'Created an interactive weather dashboard using multiple weather APIs',
      'Implemented data visualization with charts and maps for weather patterns',
      'Built historical weather data analysis with trend predictions',
      'Designed mobile-first responsive interface with offline capabilities'
    ],
    image: '/images/projects/weather-dashboard.jpg',
    gallery: [
      '/images/projects/weather-1.jpg',
      '/images/projects/weather-2.jpg',
      '/images/projects/weather-3.jpg',
      '/images/projects/weather-4.jpg'
    ],
    technologies: ['React', 'D3.js', 'OpenWeather API', 'Chart.js', 'PWA'],
    tags: ['Analytics', 'Data Visualization', 'API Integration', 'PWA'],
    liveUrl: 'https://weather-analytics.aftabpathan.dev',
    githubUrl: 'https://github.com/aftab0khan021/weather-dashboard',
    category: 'web-app',
    featured: true,
    order: 2,
    isActive: true,
    completedDate: '2023-07-10',
    status: 'completed',
  },
  {
    _id: 'project-4',
    name: 'Portfolio CMS',
    description: 'A headless CMS solution for portfolio websites with content management and API generation.',
    longDescription: [
      'Built a headless CMS specifically designed for portfolio and personal websites',
      'Implemented drag-and-drop content builder with live preview functionality',
      'Created automatic API generation for seamless frontend integration',
      'Designed scalable architecture supporting multiple portfolio sites'
    ],
    image: '/images/projects/portfolio-cms.jpg',
    gallery: ['/images/projects/cms-1.jpg', '/images/projects/cms-2.jpg'],
    technologies: ['Next.js', 'Sanity', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    tags: ['CMS', 'API', 'Headless', 'Portfolio'],
    liveUrl: 'https://portfolio-cms.aftabpathan.dev',
    githubUrl: 'https://github.com/aftab0khan021/portfolio-cms',
    category: 'web-app',
    featured: false,
    order: 3,
    isActive: true,
    completedDate: '2024-01-20',
    status: 'completed',
  },
];

export const mockSkills = [
  // Frontend Development
  {
    _id: 'skill-1',
    name: 'React',
    level: 95,
    category: 'Frontend Development',
    color: '#61DAFB',
    yearsOfExperience: 4,
    featured: true,
    order: 0,
    isActive: true,
  },
  {
    _id: 'skill-2',
    name: 'TypeScript',
    level: 90,
    category: 'Frontend Development',
    color: '#3178C6',
    yearsOfExperience: 3,
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    _id: 'skill-3',
    name: 'Next.js',
    level: 88,
    category: 'Frontend Development',
    color: '#000000',
    yearsOfExperience: 2,
    featured: true,
    order: 2,
    isActive: true,
  },
  {
    _id: 'skill-4',
    name: 'Vue.js',
    level: 82,
    category: 'Frontend Development',
    color: '#4FC08D',
    yearsOfExperience: 2,
    featured: false,
    order: 3,
    isActive: true,
  },
  {
    _id: 'skill-5',
    name: 'Tailwind CSS',
    level: 92,
    category: 'Frontend Development',
    color: '#06B6D4',
    yearsOfExperience: 3,
    featured: true,
    order: 4,
    isActive: true,
  },
  
  // Backend Development
  {
    _id: 'skill-6',
    name: 'Node.js',
    level: 90,
    category: 'Backend Development',
    color: '#339933',
    yearsOfExperience: 4,
    featured: true,
    order: 0,
    isActive: true,
  },
  {
    _id: 'skill-7',
    name: 'Express.js',
    level: 88,
    category: 'Backend Development',
    color: '#000000',
    yearsOfExperience: 4,
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    _id: 'skill-8',
    name: 'FastAPI',
    level: 85,
    category: 'Backend Development',
    color: '#009688',
    yearsOfExperience: 2,
    featured: false,
    order: 2,
    isActive: true,
  },
  {
    _id: 'skill-9',
    name: 'GraphQL',
    level: 78,
    category: 'Backend Development',
    color: '#E10098',
    yearsOfExperience: 2,
    featured: false,
    order: 3,
    isActive: true,
  },

  // Database
  {
    _id: 'skill-10',
    name: 'MongoDB',
    level: 87,
    category: 'Database',
    color: '#47A248',
    yearsOfExperience: 4,
    featured: true,
    order: 0,
    isActive: true,
  },
  {
    _id: 'skill-11',
    name: 'PostgreSQL',
    level: 83,
    category: 'Database',
    color: '#336791',
    yearsOfExperience: 3,
    featured: false,
    order: 1,
    isActive: true,
  },
  {
    _id: 'skill-12',
    name: 'Redis',
    level: 75,
    category: 'Database',
    color: '#DC382D',
    yearsOfExperience: 2,
    featured: false,
    order: 2,
    isActive: true,
  },

  // DevOps & Tools
  {
    _id: 'skill-13',
    name: 'Docker',
    level: 82,
    category: 'DevOps & Tools',
    color: '#2496ED',
    yearsOfExperience: 3,
    featured: true,
    order: 0,
    isActive: true,
  },
  {
    _id: 'skill-14',
    name: 'AWS',
    level: 78,
    category: 'DevOps & Tools',
    color: '#FF9900',
    yearsOfExperience: 2,
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    _id: 'skill-15',
    name: 'Git',
    level: 92,
    category: 'DevOps & Tools',
    color: '#F05032',
    yearsOfExperience: 5,
    featured: true,
    order: 2,
    isActive: true,
  },

  // Programming Languages
  {
    _id: 'skill-16',
    name: 'JavaScript',
    level: 93,
    category: 'Programming Languages',
    color: '#F7DF1E',
    yearsOfExperience: 5,
    featured: true,
    order: 0,
    isActive: true,
  },
  {
    _id: 'skill-17',
    name: 'Python',
    level: 85,
    category: 'Programming Languages',
    color: '#3776AB',
    yearsOfExperience: 3,
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    _id: 'skill-18',
    name: 'Java',
    level: 75,
    category: 'Programming Languages',
    color: '#ED8B00',
    yearsOfExperience: 2,
    featured: false,
    order: 2,
    isActive: true,
  },
];

export const mockCertifications = [
  {
    _id: 'cert-1',
    name: 'AWS Certified Developer - Associate',
    issuer: 'Amazon Web Services',
    issueDate: '2023-08-15',
    expiryDate: '2026-08-15',
    credentialId: 'AWS-CDA-2023-001',
    credentialUrl: 'https://aws.amazon.com/verification/001',
    image: '/images/certifications/aws-developer.jpg',
    description: 'Demonstrates proficiency in developing and maintaining applications on AWS platform with focus on security, performance, and cost optimization.',
    skills: ['AWS Lambda', 'DynamoDB', 'S3', 'API Gateway', 'CloudFormation'],
    category: 'cloud',
    order: 0,
    featured: true,
    isActive: true,
  },
  {
    _id: 'cert-2',
    name: 'MongoDB Certified Developer',
    issuer: 'MongoDB Inc.',
    issueDate: '2023-03-22',
    expiryDate: '2026-03-22',
    credentialId: 'MDB-DEV-2023-002',
    credentialUrl: 'https://university.mongodb.com/certification/002',
    image: '/images/certifications/mongodb-developer.jpg',
    description: 'Validates expertise in MongoDB database design, development, and deployment for modern applications.',
    skills: ['MongoDB', 'Mongoose', 'Aggregation Pipeline', 'Indexing', 'Replica Sets'],
    category: 'database',
    order: 1,
    featured: true,
    isActive: true,
  },
  {
    _id: 'cert-3',
    name: 'React Professional Certificate',
    issuer: 'Meta',
    issueDate: '2022-11-10',
    expiryDate: null,
    credentialId: 'META-REACT-2022-003',
    credentialUrl: 'https://coursera.org/verify/professional-cert/003',
    image: '/images/certifications/meta-react.jpg',
    description: 'Comprehensive certification covering React fundamentals, advanced patterns, and professional development practices.',
    skills: ['React', 'JSX', 'Hooks', 'Context API', 'Redux', 'Testing'],
    category: 'programming',
    order: 2,
    featured: true,
    isActive: true,
  },
  {
    _id: 'cert-4',
    name: 'Google Cloud Platform Fundamentals',
    issuer: 'Google Cloud',
    issueDate: '2023-01-18',
    expiryDate: '2026-01-18',
    credentialId: 'GCP-FUND-2023-004',
    credentialUrl: 'https://cloud.google.com/certification/004',
    image: '/images/certifications/gcp-fundamentals.jpg',
    description: 'Foundation certification covering core GCP services, architecture patterns, and cloud computing principles.',
    skills: ['Compute Engine', 'App Engine', 'Cloud Storage', 'BigQuery', 'Kubernetes Engine'],
    category: 'cloud',
    order: 3,
    featured: false,
    isActive: true,
  },
];

export const mockEducation = [
  {
    _id: 'edu-1',
    degree: 'Bachelor of Engineering',
    field: 'Computer Science',
    institution: 'University of Mumbai',
    location: 'Mumbai, India',
    startDate: '2016-06-01',
    endDate: '2020-05-31',
    current: false,
    status: 'completed',
    gpa: '8.2/10',
    description: 'Specialized in software engineering with focus on web technologies, algorithms, and database systems.',
    achievements: [
      'First Class with Distinction',
      'Best Final Year Project Award',
      'Technical Society Secretary',
      'Dean\'s List - 4 semesters'
    ],
    relevantCourses: [
      'Data Structures & Algorithms',
      'Web Technologies',
      'Database Management Systems',
      'Software Engineering',
      'Computer Networks',
      'Operating Systems',
      'Object-Oriented Programming'
    ],
    logo: '/images/education/university-mumbai.jpg',
    order: 0,
    isActive: true,
  },
  {
    _id: 'edu-2',
    degree: 'Higher Secondary Certificate',
    field: 'Science (PCM)',
    institution: 'Mumbai College of Science',
    location: 'Mumbai, India',
    startDate: '2014-06-01',
    endDate: '2016-05-31',
    current: false,
    status: 'completed',
    gpa: '85%',
    description: 'Mathematics and Physics major with computer science elective. Foundation in analytical thinking and problem-solving.',
    achievements: [
      'Science Olympiad Gold Medal',
      'Mathematics Excellence Award',
      'Perfect Attendance Award'
    ],
    relevantCourses: [
      'Advanced Mathematics',
      'Physics',
      'Chemistry',
      'Computer Science',
      'Statistics'
    ],
    logo: '/images/education/mumbai-college.jpg',
    order: 1,
    isActive: true,
  },
];

// Group skills by category for easier consumption
export const mockSkillsByCategory = mockSkills.reduce((acc, skill) => {
  const category = skill.category.toLowerCase().replace(/[\s&]/g, '_');
  if (!acc[category]) {
    acc[category] = [];
  }
  acc[category].push(skill);
  return acc;
}, {} as Record<string, typeof mockSkills>);